In [1]:
import pandas as pd
import numpy as np
import random

In [ ]:
#1¿Qué diferencia hay entre una Serie y un DataFrame?
#Las series son unidimensionales y los DataFrame bidimensionales

In [ ]:
#2. Momento de trabajar con Series. Contesta a las siguientes preguntas: 
#Crea dos listas:
#Una que se llame "valores" que tenga 7 números aleatorios.
#Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [25]:
valores = random.sample(range(1,20),7)
print(valores)
indices =["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"]
print(indices)

[10, 1, 18, 13, 16, 8, 12]
['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo']


In [26]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.
serie = pd.Series(valores, index = ["lunes","martes","miércoles","jueves","viernes", "sábado", "domingo"])
print(serie)

lunes        10
martes        1
miércoles    18
jueves       13
viernes      16
sábado        8
domingo      12
dtype: int64


In [57]:
#A partir de las dos listas anteriores crea un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez.
lista_zip =zip(indices, valores)


diccionario ={}
for indice, valor in lista_zip:
    diccionario[indice]= valor   
print(diccionario)

    
#Crea una Serie con el diccionario creado en el punto anterior.

serie_dic= pd.Series(diccionario)
print(serie_dic)   
    




{'lunes': 10, 'martes': 1, 'miércoles': 18, 'jueves': 13, 'viernes': 16, 'sábado': 8, 'domingo': 12}
lunes        10
martes        1
miércoles    18
jueves       13
viernes      16
sábado        8
domingo      12
dtype: int64


dtype('int64')

In [60]:
#¿Qué forma tiene esta última Serie?
serie_dic.shape

(7,)

In [61]:
#¿Qué tipo de datos?
serie_dic.dtype

dtype('int64')

In [62]:
#¿Qué tamaño tiene?

serie_dic.size

7

In [71]:
#¿Cuáles son los índices de la Serie?
serie_dic.index

Index(['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado',
       'domingo'],
      dtype='object')

In [72]:
#¿Y los values?
serie_dic.values

array([10,  1, 18, 13, 16,  8, 12])

In [73]:
#Extrae el valor para el índice "lunes"
serie_dic[0]

10

In [83]:
#Extrae el valor para el índice "lunes", "martes" y "miércoles".
serie_dic.values[0:3]


array([10,  1, 18])

In [86]:
#Extrae el valor para el índice "lunes" y "domingo".
serie_dic.values[[0,-1]]

array([10, 12])

In [ ]:
#Es el turno de los DataFrames
#Crea un array de dos dimensiones con 4 filas y 3 columnas.

In [92]:
array_nuevo =np.empty((4,3))
print(array_nuevo)
data_array =pd.DataFrame(array_nuevo)
data_array

[[4.64762259e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.10343781e-312 8.69189162e-043]
 [2.59187043e+184 2.04029348e+160 1.20854032e+161]
 [1.23184848e+165 1.10765237e-047 2.31805414e-056]]


0              1              2
0  4.647623e-310   0.000000e+00   0.000000e+00
1   0.000000e+00  1.103438e-312   8.691892e-43
2  2.591870e+184  2.040293e+160  1.208540e+161
3  1.231848e+165   1.107652e-47   2.318054e-56

In [102]:
data_columnas = data_array.set_axis(['España', 'Francia', 'Italia'], axis=1)
data_columnas

España        Francia         Italia
0  4.647623e-310   0.000000e+00   0.000000e+00
1   0.000000e+00  1.103438e-312   8.691892e-43
2  2.591870e+184  2.040293e+160  1.208540e+161
3  1.231848e+165   1.107652e-47   2.318054e-56

In [120]:
medallas = pd.read_csv("medallas.csv", index_col=0)

In [121]:
df_medallas =pd.DataFrame(medallas)
df_medallas


País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [130]:
df_medallas.loc[7,:]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [131]:
#Usando el loc extrae todas las columnas de China e Irán
df_medallas.loc[[1,4],:]

País   Oro  Plata  Bronce
1  China  1473    994     720
4   Irán   179    181     197

In [141]:
#Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
df_medallas.loc[[1,4],["Oro","Plata", "Bronce"]]

Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [143]:
# Usando el iloc extrae la información de la India. Devolved todas las columnas.
df_medallas.iloc[5]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [148]:
#Usando el iloc extrae todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte
df_medallas.iloc[1::2]

País   Oro  Plata  Bronce
2             Japón  1032   1037     985
4              Irán   179    181     197
6             India   154    202     315
8         Indonesia   112    131     240
10  Corea del Norte    91    120     235

In [154]:
#Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".
df_medallas.iloc[1::2][["Oro", "Plata", "Bronce"]]

Oro  Plata  Bronce
2   1032   1037     985
4    179    181     197
6    154    202     315
8    112    131     240
10    91    120     235

In [ ]:
#Contesta a las siguientes preguntas:
#¿Qué país consiguió más de 200 medallas de oro?

In [167]:
lista_oro_200 =df_medallas["Oro"] >200
print(lista_oro_200)
df_medallas.loc[lista_oro_200]["País"]


1      True
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
Name: Oro, dtype: bool


1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object

In [184]:
#¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
lista_oro_200 
lista_1000_plata = df_medallas["Plata"] >1000
listacondiciones = lista_oro_200 & lista_1000_plata
df_medallas.loc[listacondiciones]["País"]

2    Japón
Name: País, dtype: object

In [190]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?
lista_oro_200
lista_bronce = df_medallas["Bronce"] >700

lista_condicionesOB=lista_oro_200 | lista_bronce
df_medallas.loc[lista_condicionesOB]["País"]

1            China
2            Japón
3    Corea del Sur
Name: País, dtype: object

In [194]:
#Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.
df_medallas["total"]=df_medallas["Oro"]+df_medallas["Plata"]+df_medallas["Bronce"]

In [195]:
df_medallas

País   Oro  Plata  Bronce  total
1             China  1473    994     720   3187
2             Japón  1032   1037     985   3054
3     Corea del Sur   745    663     827   2235
4              Irán   179    181     197    557
5        Kazajistán   155    158     224    537
6             India   154    202     315    671
7         Tailandia   132    175     278    585
8         Indonesia   112    131     240    483
9      China Taipéi    99    144     276    519
10  Corea del Norte    91    120     235    446