In [1]:
import numpy as np

In [ ]:
#Creación y Indexación:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.
#Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
#Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
#Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
#Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?
#Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.
#BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [9]:
#1.Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.
array_1=np.random.randint(10,100,50)
print(array_1)
array_1[::5]

[57 41 23 96 32 29 78 90 71 84 99 27 23 55 98 44 15 27 59 76 66 24 84 73
 81 29 91 47 32 94 80 13 80 70 72 46 66 44 32 32 80 82 50 24 61 19 84 19
 73 70]


array([57, 29, 99, 44, 66, 29, 80, 46, 80, 19])

In [18]:
#2.Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
array_2 =np.random.randint(0,21,30)
print(array_2)
print("--------")
array_2[1::2]

[ 5  9 14  9 19  2  9  8  3 16  7  6 10 14  3 16  2  9 10  6 19 13 12 19
  6 20  5  2  2 14]
--------


array([ 9,  9,  2,  8, 16,  6, 14, 16,  9,  6, 13, 19, 20,  2, 14])

In [25]:
#3.Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
array_bi= np.random.rand(4,6)
print(array_bi)
print("--------")
array_bi1=array_bi.round(2)
print(array_bi1)
print("--------")
array_bi1[-1]

[[0.38218331 0.57236239 0.65648035 0.77006327 0.01969139 0.83433253]
 [0.44595656 0.67304193 0.54809339 0.95106744 0.40189208 0.34372742]
 [0.79252794 0.07781476 0.13855926 0.10726839 0.10133223 0.1465743 ]
 [0.96585333 0.09929279 0.20714128 0.5956665  0.49505516 0.30205433]]
--------
[[0.38 0.57 0.66 0.77 0.02 0.83]
 [0.45 0.67 0.55 0.95 0.4  0.34]
 [0.79 0.08 0.14 0.11 0.1  0.15]
 [0.97 0.1  0.21 0.6  0.5  0.3 ]]
--------


array([0.97, 0.1 , 0.21, 0.6 , 0.5 , 0.3 ])

In [27]:
#4.Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
array_bi2= np.random.rand(6,4)
print(array_bi2)
print("--------")
array_bi2_1=array_bi.round(2)
print(array_bi2_1)
print("--------")
array_bi1[1]

[[0.90727642 0.96000848 0.41784552 0.6152497 ]
 [0.12448727 0.75679414 0.52901031 0.43436522]
 [0.90505908 0.75087159 0.82182514 0.51755172]
 [0.19698428 0.40158274 0.53452304 0.41774203]
 [0.92354968 0.10696452 0.85916347 0.14459727]
 [0.87160941 0.89809843 0.04631162 0.93974754]]
--------
[[0.38 0.57 0.66 0.77 0.02 0.83]
 [0.45 0.67 0.55 0.95 0.4  0.34]
 [0.79 0.08 0.14 0.11 0.1  0.15]
 [0.97 0.1  0.21 0.6  0.5  0.3 ]]
--------


array([0.45, 0.67, 0.55, 0.95, 0.4 , 0.34])

In [39]:
#5.Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
array_uni = np.random.randint(-50,50,30)
print(array_uni)
print("--------")
condicion = array_uni < 0
print(condicion)
print("--------")
np.where(condicion, "negativo","positivo")


[-19  25 -38   5 -45  25 -43   8  43 -41 -35 -30  46 -26  22  14  35   0
  28 -20 -21  -9  -3  -9 -40  39  -5  39  49  33]
--------
[ True False  True False  True False  True False False  True  True  True
 False  True False False False False False  True  True  True  True  True
  True False  True False False False]
--------


array(['negativo', 'positivo', 'negativo', 'positivo', 'negativo',
       'positivo', 'negativo', 'positivo', 'positivo', 'negativo',
       'negativo', 'negativo', 'positivo', 'negativo', 'positivo',
       'positivo', 'positivo', 'positivo', 'positivo', 'negativo',
       'negativo', 'negativo', 'negativo', 'negativo', 'negativo',
       'positivo', 'negativo', 'positivo', 'positivo', 'positivo'],
      dtype='<U8')

In [45]:
#6.Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?
array_uni1 = np.random.sample(10)
print(array_uni1)
print("--------")
array_1_round= array_uni1.round(2)
print(array_1_round)
condicion2 = array_1_round > 0.5
print(condicion2)
print("--------")
print("La posición de los valores >0.5 es:", np.where(condicion2))


[0.21326641 0.70260847 0.48336485 0.55331549 0.33739042 0.91812552
 0.12802896 0.79319689 0.23939245 0.40791034]
--------
[0.21 0.7  0.48 0.55 0.34 0.92 0.13 0.79 0.24 0.41]
[False  True False  True False  True False  True False False]
--------
La posición de los valores >0.5 es: (array([1, 3, 5, 7], dtype=int64),)


In [56]:
#7.Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.
array_uni2 = np.random.randint(0,101,40)
print(array_uni2)
print("-------- Divisibles entre 3--------")
divisible3 = array_uni2 % 3
print("-------- ")
condicion_divisible = divisible3 ==0
print("Los elementos divisibles por 3 son",array_uni2[condicion_divisible])
print("-------- Divisibles entre 4--------")
divisible4 = array_uni2 % 4
print("-------- ")
condicion_divisible4 = divisible4 ==0

print("Los elementos divisibles por 3 están en las posiciones:", array_uni2[condicion_divisible4])

[ 48   7  72  56  17  70 100  77  77  78  54  47  96   0  36  91   1  92
   5 100  53  81  14  68  78  88  77   8  61  10  38  46  41  33  22  75
  28  91  20  60]
-------- Divisibles entre 3--------
-------- 
Los elementos divisibles por 3 son [48 72 78 54 96  0 36 81 78 33 75 60]
-------- Divisibles entre 4--------
-------- 
Los elementos divisibles por 3 están en las posiciones: [ 48  72  56 100  96   0  36  92 100  68  88   8  28  20  60]


In [ ]:
#8.BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [ ]:
#Reshape y Transpose:
#Ejercicios con reshape:
#Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.
#Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.
#Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.
#Ejercicios con transpose:
#Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).
#Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4)
#Preguntas teóricas:
#¿Qué diferencia existe entre el reshape y el transpose?
#¿Y entre el transpose y el swapaxes?