In [2]:
import numpy as np

In [ ]:
#Creación y Indexación:
#Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.
#Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
#Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
#Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
#Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
#Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?
#Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.
#BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [9]:
#1.Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.
array_1=np.random.randint(10,100,50)
print(array_1)
array_1[::5]

[57 41 23 96 32 29 78 90 71 84 99 27 23 55 98 44 15 27 59 76 66 24 84 73
 81 29 91 47 32 94 80 13 80 70 72 46 66 44 32 32 80 82 50 24 61 19 84 19
 73 70]


array([57, 29, 99, 44, 66, 29, 80, 46, 80, 19])

In [18]:
#2.Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.
array_2 =np.random.randint(0,21,30)
print(array_2)
print("--------")
array_2[1::2]

[ 5  9 14  9 19  2  9  8  3 16  7  6 10 14  3 16  2  9 10  6 19 13 12 19
  6 20  5  2  2 14]
--------


array([ 9,  9,  2,  8, 16,  6, 14, 16,  9,  6, 13, 19, 20,  2, 14])

In [25]:
#3.Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.
array_bi= np.random.rand(4,6)
print(array_bi)
print("--------")
array_bi1=array_bi.round(2)
print(array_bi1)
print("--------")
array_bi1[-1]

[[0.38218331 0.57236239 0.65648035 0.77006327 0.01969139 0.83433253]
 [0.44595656 0.67304193 0.54809339 0.95106744 0.40189208 0.34372742]
 [0.79252794 0.07781476 0.13855926 0.10726839 0.10133223 0.1465743 ]
 [0.96585333 0.09929279 0.20714128 0.5956665  0.49505516 0.30205433]]
--------
[[0.38 0.57 0.66 0.77 0.02 0.83]
 [0.45 0.67 0.55 0.95 0.4  0.34]
 [0.79 0.08 0.14 0.11 0.1  0.15]
 [0.97 0.1  0.21 0.6  0.5  0.3 ]]
--------


array([0.97, 0.1 , 0.21, 0.6 , 0.5 , 0.3 ])

In [27]:
#4.Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.
array_bi2= np.random.rand(6,4)
print(array_bi2)
print("--------")
array_bi2_1=array_bi.round(2)
print(array_bi2_1)
print("--------")
array_bi1[1]

[[0.90727642 0.96000848 0.41784552 0.6152497 ]
 [0.12448727 0.75679414 0.52901031 0.43436522]
 [0.90505908 0.75087159 0.82182514 0.51755172]
 [0.19698428 0.40158274 0.53452304 0.41774203]
 [0.92354968 0.10696452 0.85916347 0.14459727]
 [0.87160941 0.89809843 0.04631162 0.93974754]]
--------
[[0.38 0.57 0.66 0.77 0.02 0.83]
 [0.45 0.67 0.55 0.95 0.4  0.34]
 [0.79 0.08 0.14 0.11 0.1  0.15]
 [0.97 0.1  0.21 0.6  0.5  0.3 ]]
--------


array([0.45, 0.67, 0.55, 0.95, 0.4 , 0.34])

In [39]:
#5.Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.
array_uni = np.random.randint(-50,50,30)
print(array_uni)
print("--------")
condicion = array_uni < 0
print(condicion)
print("--------")
np.where(condicion, "negativo","positivo")


[-19  25 -38   5 -45  25 -43   8  43 -41 -35 -30  46 -26  22  14  35   0
  28 -20 -21  -9  -3  -9 -40  39  -5  39  49  33]
--------
[ True False  True False  True False  True False False  True  True  True
 False  True False False False False False  True  True  True  True  True
  True False  True False False False]
--------


array(['negativo', 'positivo', 'negativo', 'positivo', 'negativo',
       'positivo', 'negativo', 'positivo', 'positivo', 'negativo',
       'negativo', 'negativo', 'positivo', 'negativo', 'positivo',
       'positivo', 'positivo', 'positivo', 'positivo', 'negativo',
       'negativo', 'negativo', 'negativo', 'negativo', 'negativo',
       'positivo', 'negativo', 'positivo', 'positivo', 'positivo'],
      dtype='<U8')

In [45]:
#6.Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?
array_uni1 = np.random.sample(10)
print(array_uni1)
print("--------")
array_1_round= array_uni1.round(2)
print(array_1_round)
condicion2 = array_1_round > 0.5
print(condicion2)
print("--------")
print("La posición de los valores >0.5 es:", np.where(condicion2))


[0.21326641 0.70260847 0.48336485 0.55331549 0.33739042 0.91812552
 0.12802896 0.79319689 0.23939245 0.40791034]
--------
[0.21 0.7  0.48 0.55 0.34 0.92 0.13 0.79 0.24 0.41]
[False  True False  True False  True False  True False False]
--------
La posición de los valores >0.5 es: (array([1, 3, 5, 7], dtype=int64),)


In [56]:
#7.Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.
array_uni2 = np.random.randint(0,101,40)
print(array_uni2)
print("-------- Divisibles entre 3--------")
divisible3 = array_uni2 % 3
print("-------- ")
condicion_divisible = divisible3 ==0
print("Los elementos divisibles por 3 son",array_uni2[condicion_divisible])
print("-------- Divisibles entre 4--------")
divisible4 = array_uni2 % 4
print("-------- ")
condicion_divisible4 = divisible4 ==0

print("Los elementos divisibles por 4v son:", array_uni2[condicion_divisible4])

[ 48   7  72  56  17  70 100  77  77  78  54  47  96   0  36  91   1  92
   5 100  53  81  14  68  78  88  77   8  61  10  38  46  41  33  22  75
  28  91  20  60]
-------- Divisibles entre 3--------
-------- 
Los elementos divisibles por 3 son [48 72 78 54 96  0 36 81 78 33 75 60]
-------- Divisibles entre 4--------
-------- 
Los elementos divisibles por 3 están en las posiciones: [ 48  72  56 100  96   0  36  92 100  68  88   8  28  20  60]


In [ ]:
#8.BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.
array_8=np.random.randint(0,101,(2,3,5))
print(array_8)
condicion8 = array_8%3==0
numeros_condicion =array_8[condicion8]
print("---------------")
print(f"Los números que cumplen condición son{numeros_condicion}")
print("-------- Divisibles entre 3 y su reemplazo--------")
reemplazar =np.where(condicion8, 0, array_8)
print(reemplazar)

In [ ]:
#Reshape y Transpose:
#Ejercicios con reshape

In [17]:

#1Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.
array_tri = np.random.randint(0,101,(2, 3, 4))
print(array_tri)
print("------------")
array_tri.reshape(6,4)


[[[71 82 55 85]
  [19 77 52 25]
  [46 65 81 22]]

 [[89 42 41 73]
  [70 29 13 53]
  [48 75 12 67]]]
------------


array([[71, 82, 55, 85],
       [19, 77, 52, 25],
       [46, 65, 81, 22],
       [89, 42, 41, 73],
       [70, 29, 13, 53],
       [48, 75, 12, 67]])

In [7]:
#2.Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

array_3D_2 =np.random.randint(1,60,(3,4,5))
print(array_3D_2)
array_reshape = np.reshape(array_3D_2,(20,3))
print("------------------")
print(f"el nuevo array es\n{array_reshape}")
dimensiones = array_reshape.shape
dimensiones

[[[15 21 18 52 36]
  [16 48  9  8 52]
  [48 23 58 35 22]
  [32 19  5 26 30]]

 [[45  3  9 36  2]
  [29 41 17  8  1]
  [ 8 14 26 24 30]
  [ 7 30 38  9 19]]

 [[10 57 25 37  3]
  [34 39  7 15 14]
  [29 55 16 45 48]
  [23 34 41 26 34]]]
------------------
el nuevo array es
[[15 21 18]
 [52 36 16]
 [48  9  8]
 [52 48 23]
 [58 35 22]
 [32 19  5]
 [26 30 45]
 [ 3  9 36]
 [ 2 29 41]
 [17  8  1]
 [ 8 14 26]
 [24 30  7]
 [30 38  9]
 [19 10 57]
 [25 37  3]
 [34 39  7]
 [15 14 29]
 [55 16 45]
 [48 23 34]
 [41 26 34]]


(20, 3)

In [39]:
#3Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.
array_tri_ale = np.random.random_sample((4,3,2))
print(array_tri_ale)
print("------------")
array_tri_ale.size
reshape_array_tri =array_tri_ale.reshape(12,2)
print(reshape_array_tri)


[[[0.44013708 0.13704109]
  [0.93318942 0.30549451]
  [0.09112171 0.07636289]]

 [[0.82594302 0.52767583]
  [0.43972912 0.04711756]
  [0.44153465 0.73624911]]

 [[0.31550932 0.05752488]
  [0.53689474 0.78794401]
  [0.0378997  0.07100189]]

 [[0.0746326  0.56993294]
  [0.0827389  0.97831657]
  [0.37973481 0.01484732]]]
------------
[[0.44013708 0.13704109]
 [0.93318942 0.30549451]
 [0.09112171 0.07636289]
 [0.82594302 0.52767583]
 [0.43972912 0.04711756]
 [0.44153465 0.73624911]
 [0.31550932 0.05752488]
 [0.53689474 0.78794401]
 [0.0378997  0.07100189]
 [0.0746326  0.56993294]
 [0.0827389  0.97831657]
 [0.37973481 0.01484732]]


In [ ]:
#Ejercicios de transpose

In [10]:
#4.Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3)
print(array_3D_2)
transpose_array= np.transpose(array_3D_2,(2,1,0))
print("------------------")
print(transpose_array)

[[[15 21 18 52 36]
  [16 48  9  8 52]
  [48 23 58 35 22]
  [32 19  5 26 30]]

 [[45  3  9 36  2]
  [29 41 17  8  1]
  [ 8 14 26 24 30]
  [ 7 30 38  9 19]]

 [[10 57 25 37  3]
  [34 39  7 15 14]
  [29 55 16 45 48]
  [23 34 41 26 34]]]
------------------
[[[15 45 10]
  [16 29 34]
  [48  8 29]
  [32  7 23]]

 [[21  3 57]
  [48 41 39]
  [23 14 55]
  [19 30 34]]

 [[18  9 25]
  [ 9 17  7]
  [58 26 16]
  [ 5 38 41]]

 [[52 36 37]
  [ 8  8 15]
  [35 24 45]
  [26  9 26]]

 [[36  2  3]
  [52  1 14]
  [22 30 48]
  [30 19 34]]]


In [40]:
#5Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4)
array_tri_ale = np.random.random_sample((4,3,2))
print(array_tri_ale)
print("------------")
print(array_tri_ale.transpose()) # array_tri_ale (2,4,3)

[[[0.79931802 0.52594038]
  [0.18584387 0.98212028]
  [0.5893771  0.82444137]]

 [[0.09782378 0.43520306]
  [0.53181512 0.55728156]
  [0.21072731 0.62455253]]

 [[0.55293639 0.55271941]
  [0.23976195 0.52909863]
  [0.73130572 0.99905469]]

 [[0.74746375 0.52708998]
  [0.50120927 0.39469181]
  [0.94118747 0.40136046]]]
------------
[[[0.79931802 0.09782378 0.55293639 0.74746375]
  [0.18584387 0.53181512 0.23976195 0.50120927]
  [0.5893771  0.21072731 0.73130572 0.94118747]]

 [[0.52594038 0.43520306 0.55271941 0.52708998]
  [0.98212028 0.55728156 0.52909863 0.39469181]
  [0.82444137 0.62455253 0.99905469 0.40136046]]]


In [ ]:
#Preguntas teóricas

In [ ]:
#6¿Qué diferencia existe entre el reshape y el transpose?
#Mientras que reshape sirve para cambiar la forma del array sin cambiar sus datos(ni el orden), transpose se utiliza para intercambiar las dimensiones del array y supone a su vez cambio del orden de los elementos
#7.¿Y entre el transpose y el swapaxes?
# El transpose cambia la forma de la matriz,cambiando el orden de filas y columnas, manteniendo el numero de dimensiones. Mientras que el swapaxessolo cambia 2 ejes específicos de un array.

In [ ]:
#Funciones Aritméticas y Estadísticas:

In [45]:
# 1.Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

array0 = np.random.random_sample((2,3,5))
array_ej = array0.round(1)
print(array_ej)
print("------------")



[[[0.4 0.2 1.  0.9 0. ]
  [0.4 0.4 0.9 0.7 0.3]
  [0.7 0.9 0.5 0.1 0.1]]

 [[0.3 0.8 0.3 0.5 1. ]
  [1.  1.  0.1 0.5 0. ]
  [0.6 0.9 0.9 1.  0.2]]]
------------


In [71]:
#2.Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. 
#Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos
#en los valores del primer array bajo las siguientes condiciones:

b_array = np.random.random_sample((2,3,5))
array_ej1 = b_array.round(2)
print(array_ej1)
print("------------")

#Si el valor del array es igual que la media, se reemplaza por "A".
media = round(np.mean(array_ej1),1)
print("La media del array es", media)
print("------------")
condicion_a = media == array_ej1
array_A= np.where(condicion_a, "A", [array_ej1])
print(array_A)
#Si el valor del array es mayor que la media, se reemplaza por "B".
print("------------")
condicion_b =  array_ej1 > media
array_AB= np.where(condicion_b, "B", [array_A])
print(array_AB)

#Si el valor del array es menor que la media, se reemplaza por "C".

print("------------")
condicion_c =  array_ej1 < media
array_ABC= np.where(condicion_c, "C", [array_AB])
print(array_ABC)
#Si el valor es igual que el máximo, se reemplaza por "D".
print("------------")
valor_max = np.max(array_ej1)
print("El valor máximo es" , valor_max)
condicion_d =  array_ej1 == valor_max 
array_ABCD= np.where(condicion_d, "D", [array_ABC])
print(array_ABCD)


#Si el valor es igual que el mínimo, se reemplaza por "E".

print("------------")
valor_min = np.min(array_ej1)
print("El valor mínimo es" , valor_min)
condicion_e =  array_ej1 == valor_min
array_ABCDE= np.where(condicion_e, "E", [array_ABCD])
print(array_ABCDE)



[[[0.47 0.04 0.6  0.68 0.14]
  [0.89 0.22 0.76 0.82 0.02]
  [0.81 0.55 0.75 0.41 0.77]]

 [[0.5  0.89 0.45 0.01 0.21]
  [0.57 0.54 0.91 0.72 0.59]
  [0.05 0.96 0.8  0.32 0.09]]]
------------
La media del array es 0.5
------------
[[[['0.47' '0.04' '0.6' '0.68' '0.14']
   ['0.89' '0.22' '0.76' '0.82' '0.02']
   ['0.81' '0.55' '0.75' '0.41' '0.77']]

  [['A' '0.89' '0.45' '0.01' '0.21']
   ['0.57' '0.54' '0.91' '0.72' '0.59']
   ['0.05' '0.96' '0.8' '0.32' '0.09']]]]
------------
[[[[['0.47' '0.04' 'B' 'B' '0.14']
    ['B' '0.22' 'B' 'B' '0.02']
    ['B' 'B' 'B' '0.41' 'B']]

   [['A' 'B' '0.45' '0.01' '0.21']
    ['B' 'B' 'B' 'B' 'B']
    ['0.05' 'B' 'B' '0.32' '0.09']]]]]
------------
[[[[[['C' 'C' 'B' 'B' 'C']
     ['B' 'C' 'B' 'B' 'C']
     ['B' 'B' 'B' 'C' 'B']]

    [['A' 'B' 'C' 'C' 'C']
     ['B' 'B' 'B' 'B' 'B']
     ['C' 'B' 'B' 'C' 'C']]]]]]
------------
El valor máximo es 0.96
[[[[[[['C' 'C' 'B' 'B' 'C']
      ['B' 'C' 'B' 'B' 'C']
      ['B' 'B' 'B' 'C' 'B']]

     [['A' 'B'